# Generated by Django 3.2.4 on 2023-01-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='prueba', max_length=200),
            preserve_default=False,
        ),
    ]
